### ISSUE TITLE
Lua 5.x version ?

### ISSUE THREAD

**Issue by nodecentral** [Bowuigi/BannerDesigner#1]
Hi

Love the idea, I’m new to Lua, but I’m just wondering if you had a pure Lua version, as I can see this one is for Luajit. (#!/usr/bin/luajit_ ?When I tried it on mind, Lua 5.2 - this occurred.
````
pi@raspberrypi:/ $ lua home/pi/shared/banner.lua
sh: 1: figlet: not found

**Comment by Bowuigi** [comment]
Oh, that is not a lua problem, you need figlet for this.
Install with "sudo apt install figlet"
